name: Release

on:
  push:
    branches:
      - feature/forge
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        arch: ['x64', 'arm64']
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Build and Publish
      run: npx electron-forge publish --arch=x64
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        ELECTRON_ARCH: ${{ matrix.arch }} 
