name: Release

on:
  push:
    branches:
      - feature/forge
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        arch: ['x64', 'arm64']
    steps:
    - uses: actions/checkout@v4
    - name: Install and Build
      run: npm install && npm run make
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        ELECTRON_ARCH: ${{ matrix.arch }} 
